# provisioning/roles/system/vars/main.yml
#
# Variables for system provisioning.

---
# the name of the vagrant user
vagrant_user: "vagrant"

# the home directory
vagrant_user_home: "/home/{{vagrant_user}}"

# directory for dotfile repos
dotfiles: "{{ vagrant_user_home }}/.dotfiles"

# git repository for zsh dotfiles
zsh_git_url: "https://github.com/enil/enil-zsh-dotfiles.git"

# git repository for vim dotfiles
vim_git_url: "https://github.com/enil/enil-vim-dotfiles.git"

# zsh dotfile directory
zsh_dotfiles: "{{ dotfiles }}/zsh"

# vim dotfile directory
vim_dotfiles: "{{ dotfiles }}/vim"

# username for git
git_username: "jsmith"

# email for git
git_email: "jsmith@example.com"

# whether outdated repos should be updated
update_repos: no

# additional packages to install
extra_packages: []

