# provisioning/roles/system/tasks/system.yml
#
# Basic system provisioning.

---
- name: Install required packages
  apt: name={{ item }}
  with_items:
    - git
    - zsh
    - vim
  sudo: yes

# set up zsh
- apt: name=zsh
  sudo: yes

- name: Download zsh dotfiles
  git: repo={{ zsh_git_url }} dest={{ zsh_dotfiles }} update={{ update_repos }}

- name: Add zsh files to home directory
  file: src={{ zsh_dotfiles }}/{{ item }} dest={{ vagrant_user_home}}/{{ item }} state=link force=yes
  with_items:
    - .zsh
    - .zshrc

- name: Set shell to zsh
  user: name={{ vagrant_user }} shell=/bin/zsh
  sudo: yes

# set up vim
- name: Download vim dotfiles
  git: repo={{ vim_git_url }} dest={{ vim_dotfiles }} update={{ update_repos }}

- name: Add vim files to home directory
  file: src={{ vim_dotfiles }}/{{ item }} dest={{ vagrant_user_home }}/{{ item }} state=link force=yes
  with_items:
    - .vim
    - .vimrc

# set up git
- name: Set up gitconfig
  template: src=git/gitconfig dest={{ vagrant_user_home }}/.gitconfig mode=0600 backup=yes

# additional packages
- name: Install packages {{ extra_packages }}
  apt: name={{ item }}
  with_items: extra_packages
  sudo: yes

- name: Set up SSH keys
  user: name={{ vagrant_user }} generate_ssh_key=yes

- name: Set up locale
  template: src=misc/locale dest=/etc/default/locale
  sudo: yes

