# provisioning/roles/system/tasks/main.yml
#
# Basic system provisioning.

---
- name: Remove cloud-init
  apt: name=cloud-init state=absent purge=yes
  sudo: yes

- name: Set apt mirrors
  template: src=misc/sources.list dest=/etc/apt/sources.list
  sudo: yes

- name: Update apt
  apt: update_cache=yes
  sudo: yes

# additional packages
- name: Install packages {{ extra_packages }}
  apt: name={{ item }}
  with_items: extra_packages
  sudo: yes

- name: Set up SSH keys
  user: name={{ vagrant_user }} generate_ssh_key=yes

- name: Set up locale
  template: src=misc/locale dest=/etc/default/locale
  sudo: yes

