# provisioning/roles/system/tasks/main.yml
#
# Basic system provisioning.

---
# additional packages
- name: Install packages {{ extra_packages }}
  apt: name={{ item }}
  with_items: extra_packages
  sudo: yes

- name: Set up SSH keys
  user: name={{ vagrant_user }} generate_ssh_key=yes

- name: Set up locale
  template: src=misc/locale dest=/etc/default/locale
  sudo: yes

