# provisioning/roles/system/tasks/system.yml
#
# Basic system provisioning.

---
- name: Install required packages
  apt: name={{ item }}
  with_items:
    - git
    - zsh
    - vim

# set up zsh
- apt: name=zsh

- name: Download zsh dotfiles
  git: repo={{ zsh_git_url }} dest={{ zsh_dotfiles }} update={{ update_repos }}

- name: Add zsh files to home directory
  file: src={{ zsh_dotfiles }}/{{ item }} dest={{ item }} state=link force=yes
  with_items:
    - .zsh
    - .zshrc

- name: Set shell to zsh
  user: name={{ vagrant_user }} shell=/bin/zsh

# set up vim
- name: Download vim dotfiles
  git: repo={{ vim_git_url }} dest={{ vim_dotfiles }} update={{ update_repos }}

- name: Add vim files to home directory
  file: src={{ vim_dotfiles }}/{{ item }} dest={{ item }} state=link force=yes
  with_items:
    - .vim
    - .vimrc

# additional packages
- name: Install packages {{ extra_packages }}
  apt: name={{ item }}
  with_items: extra_packages

- name: Set up SSH keys
  user: name={{ vagrant_user }} generate_ssh_key=yes

