# provisioning/roles/vim/tasks/main.yml
#
# Provisioning for vim.

---
- name: Install vim
  apt: name=vim
  sudo: yes

- name: Download vim dotfiles
  git: repo={{ vim_git_url }} dest={{ vim_dotfiles_dir }} update={{ update_repos }}

- name: Link vim dotfiles
  file: src={{ vim_dotfiles_dir }}/{{ item }} dest={{ vagrant_user_home }}/{{ item }} state=link force=yes
  with_items: vim_dotfiles

