# system.yml
#
# Basic system provisioning.

---
- hosts: all
  vars:
    # directory for dotfile repos
    dotfiles: ".dotfiles"

    # git repository for zsh dotfiles
    zsh_git_url: "https://github.com/enil/enil-zsh-dotfiles.git"

    # git repository for vim dotfiles
    vim_git_url: "https://github.com/enil/enil-vim-dotfiles.git"

    # zsh dotfile directory
    zsh_dotfiles: "{{ dotfiles }}/zsh"

    # vim dotfile directory
    vim_dotfiles: "{{ dotfiles }}/vim"

    # whether outdated repos should be updated
    update_repos: no

    # additional packages to install
    extra_packages: []

  tasks:
    - name: Install required packages
      apt: name={{ item }}
      with_items:
        - git
        - zsh
        - vim

    # set up zsh
    - apt: name=zsh

    - name: Download zsh dotfiles
      git: repo={{ zsh_git_url }} dest={{ zsh_dotfiles }} update={{ update_repos }}

    - name: Add zsh files to home directory
      file: src={{ zsh_dotfiles }}/{{ item }} dest={{ item }} state=link force=yes
      with_items:
        - .zsh
        - .zshrc

    - name: Set shell to zsh
      user: name=vagrant shell=/bin/zsh

    # set up vim
    - name: Download vim dotfiles
      git: repo={{ vim_git_url }} dest={{ vim_dotfiles }} update={{ update_repos }}

    - name: Add vim files to home directory
      file: src={{ vim_dotfiles }}/{{ item }} dest={{ item }} state=link force=yes
      with_items:
        - .vim
        - .vimrc

    # additional packages
    - name: Install packages {{ extra_packages }}
      apt: name={{ item }}
      with_items: extra_packages

