# provisioning/roles/tmux/vars/main.yml
#
# Variables for tmux provisioning.

---
# URL for the tmux dotfiles repo
tmux_git_url: "https://github.com/enil/enil-tmux-dotfiles.git"

# target directory for the tmux dotfiles
tmux_dotfiles_dir: "{{ dotfiles_dir }}/tmux"

# tmux dotfiles to link
tmux_dotfiles: [.tmux.conf]

